### ISSUE TITLE
👾 [Bug Report] +2 profession icons will be created

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#973] opened 2021-11-27 17:37 UTC
**Description**: 

**Steps to reproduce the problem**: 
1. learn first aid
![image](https://user-images.githubusercontent.com/1216225/143690730-b51bc221-533a-493b-91b2-485fad67e248.png)

~~1. add to inventory **.char add item 2589 60**~~
~~2. when you create 50 pieces **Linen Bandage** level 2 (Journeyman) will open for you~~
3. +2 profession icons will be created
![image](https://user-images.githubusercontent.com/1216225/143690987-11183444-77bd-41e5-ad23-da081a636824.png)
~~4. further learning new "Bandage" is impossible~~

~~5 for the first 50 pieces you get  -> https://www.wowhead.com/achievement=131 (points for 150)~~

**Expansion version**: 

Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 
latest dev

**Comment by Appled** [comment] 2021-11-29 22:14
> further learning new "Bandage" is impossible

This is not a bug, you learn next bandage skill at skill level 80, not at 50. Linen Bandage (skill 1) -> Heavy Linen Bandage (skill 40) -> Wool Bandage (skill 80)

**Comment by Appled** [comment] 2021-11-30 00:16
Actually this is almost duplicate of https://github.com/AscEmu/AscEmu/issues/70
Relogging cleans up the spell book

**Comment by schnek** [comment] 2021-11-30 00:56
![image](https://user-images.githubusercontent.com/1216225/143963919-663237f6-a8fa-4e1e-a3d6-52db5cee66da.png)
lvl 1

> This is not a bug, you learn next bandage skill at skill level 80, not at 50. Linen Bandage (skill 1) -> Heavy Linen Bandage (skill 40) -> Wool Bandage (skill 80)

I'm talking about bandages in general and not about recipes

![image](https://user-images.githubusercontent.com/1216225/143964388-8c0231d4-b9ee-4578-a470-e04126bcaa56.png)

lvl 2 (50) wotlk

with this you get experience points for 150 -> https://www.wowhead.com/achievement=131

after that, continued to create new dressings and from 2000 pieces created 0

perhaps it is believed that I made 150 pieces (Linen Bandage) so the chance is small

**Comment by Appled** [comment] 2022-01-09 02:45
> further learning new "Bandage" is impossible

https://github.com/AscEmu/AscEmu/pull/983 will fix this. My mistake in trainers 😄 


> 5 for the first 50 pieces you get -> https://www.wowhead.com/achievement=131 (points for 150)

That is correct achievement. Wowhead uses retail data so do not believe it. See https://wotlk.evowow.com/?achievement=131

**Comment by schnek** [comment] 2022-01-09 17:03
> > further learning new "Bandage" is impossible
> 
> #983 will fix this. My mistake in trainers 😄
> 
> > 5 for the first 50 pieces you get -> https://www.wowhead.com/achievement=131 (points for 150)
> 
> That is correct achievement. Wowhead uses retail data so do not believe it. See https://wotlk.evowow.com/?achievement=131
ok i will test in the coming days (2-4)😅

**Comment by schnek** [comment] 2022-01-13 22:40
up

**Comment by schnek** [comment] 2022-11-14 17:38
with each new achievement 3 additional icons.

**Comment by schnek** [comment] 2023-02-08 11:39
https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Packets/Handlers/MiscHandler.cpp#L348
https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Packets/Handlers/MiscHandler.cpp#L358
https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Packets/Handlers/MiscHandler.cpp#L363

if you remove "else" after exiting the game and entering you will have 1 icon

**Comment by schnek** [comment] 2024-03-09 20:05
fix [1180](https://github.com/AscEmu/AscEmu/pull/1180)

**Closed** 2024-03-09 20:52 UTC
Labels: Category: Spells/Skills, Issue - Confirmed
