### ISSUE TITLE
👾 [Bug Report] quests are taken without confirmation

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#804] opened 2020-10-12 13:18 UTC
**Description**: 

if you point to an npc with a quest, then the quest will be automatically activated (after that you can do it again)

**Steps to reproduce the problem**: 
1. go to the npc with a quest

**Expansion version**: 
Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

last dev

**Operating system**: 

Platform: Windows

**Comment by Zyres** [comment] 2020-12-20 13:21
can you give some quest examples? (entries)

**Comment by Appled** [comment] 2020-12-20 15:13
Some quests have flag QUEST_FLAGS_AUTO_ACCEPT and those quests should be automatically added to player's quest log

**Comment by schnek** [comment] 2020-12-20 18:24
for example quest 2680. accepted before you press the accept button.

**Comment by Appled** [comment] 2020-12-20 21:33
That quest id does not exist

**Comment by aaron02** [comment] 2020-12-20 21:59
arent all quests in the satrting zones since cata auto accept?

**Comment by Appled** [comment] 2020-12-21 02:18
Yes I believe so. I'd say this issue is not a bug

**Comment by Appled** [comment] 2020-12-21 02:20
Closing the issue, it's not a bug. See this video and pause it at 0:00 https://www.youtube.com/watch?v=iS5YeIKJJXM
You can see in the chat that the quest is already accepted even though the player has not clicked the accept button yet.

**Closed by Appled** 2020-12-21 02:20 UTC
Labels: Issue - Needs retesting

**Comment by schnek** [comment] 2020-12-21 02:37
https://www.youtube.com/watch?v=Bbkd8X1ruKY in our case (AE CATA), the quest is taken without pressing the button

**Comment by Appled** [comment] 2020-12-21 04:31
If you go frame by frame that video, you can see in the chat window "Quest accepted" before the player clicks accept button.
Here is a quote from C-ManGOS developer:

> 
> This is not even implemented in the core to handle this.
> 
> What should be happening is if a quest has this flag it will skip the Gossip_Id display and directly show the quest being offered and as soon as you talk to the NPC it will accept the quest and add it to the quest log for the player.
> 
> You still have the opportunity to "accept" the quest when done reading the quest but it does not change anything because it already auto accepted the quest for you. If you Close the quest gossip windows without clicking "accept" it does not change anything either as you are already accepted and on the quest.
