### ISSUE TITLE
[VMap issue] No dismounting in Brill's tavern

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#648] opened 2018-10-03 19:00 UTC
**Description**:  not dismounting in a tavern

**Steps to reproduce the problem**:
1.  Current Position: Map: 0 Zone: 0 Area: 85 Phase: 1 X: 2190.090088 Y: 262.459991 Z: 39.200001 Orientation: 1.682497
![image](https://user-images.githubusercontent.com/1216225/46432005-dd13a580-c755-11e8-8fe1-7724fc85f801.png)

2.  https://www.wowhead.com/item=46308/black-skeletal-horse (any mount)
![image](https://user-images.githubusercontent.com/1216225/46433429-81e3b200-c759-11e8-8420-ce250dd23520.png)
![image](https://user-images.githubusercontent.com/1216225/46432239-6dea8100-c756-11e8-83b2-70e3a3b5a414.png)

3. Current Position: Map: 0 Zone: 85 Area: 159 Phase: 1 X: 2273.755127 Y: 284.075867 Z: 34.977123 Orientation: 6.103842 
![image](https://user-images.githubusercontent.com/1216225/46433111-b4d97600-c758-11e8-99dc-19a3d2befbc3.png)

![image](https://user-images.githubusercontent.com/1216225/46433247-097cf100-c759-11e8-8327-7faa68edae7c.png)

![image](https://user-images.githubusercontent.com/1216225/46433326-3df0ad00-c759-11e8-8f91-409ab82cc58d.png)

**Version**:   <= WotLK

**AscEmu hash/commit**: last commit develop 

**Operating system**:  win10

**Comment by Appled** [comment] 2018-10-03 19:01
Works for me on older revision.
Do you have these set to '1' https://github.com/AscEmu/AscEmu/blob/develop/src/configs/world.conf.in#L701 ?

**Comment by schnek** [comment] 2018-10-03 19:05
```
<Terrain UnloadMaps  = "1"
         Collision   = "1"
         Pathfinding = "1">
```
Perhaps it is worth explaining that this problem is in this place.


upd 5sec

**Comment by Appled** [comment] 2018-10-03 19:11
Interesting. Let me get new develop and test.

**Comment by Appled** [comment] 2018-10-03 22:17
Confirmed. You don't automatically dismount indoors but you can't remount indoors if you dismounted

**Comment by Appled** [comment] 2022-05-10 16:20
Fixed in https://github.com/AscEmu/AscEmu/commit/d1f180970f80f00c961f5a96349e33af98728bc6

**Closed by Appled** 2022-05-10 16:20 UTC
Labels: Core - Map/Area Management
