### ISSUE TITLE
Blood Presence bug

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#256] opened 2016-01-24 02:13 UTC
Healed by 4% of damage dealt. <- this part does not work.
Spell ID: 48266

need to add either into hackfixes.cpp or a different method. The proc spell id is (Non-Existing) ???
Apply Aura: Proc Trigger Spell 
Proc Spell ID: 1206
Value: 4

**Comment by Lectro** [comment] 2016-02-21 17:05
I'm sure its bug caused by heal effect actually because healing effect is scripted exclusivelly in this effect script and just instead of adding more hacks, fix this this effect instead

**Comment by Appled** [comment] 2021-11-30 22:11
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa

**Closed by Appled** 2021-11-30 22:11 UTC
Labels: Category: Spells/Skills, Patch 3.3.5 - WoTLK
