### ISSUE TITLE
Restoration not work.

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#237] opened 2016-01-17 14:46 UTC
Restoration does not work in any of the battlefields.
Restoration - Restores 10% of your health and mana every second for 10 seconds. Attacking or being attacked will cancel the effect. http://wowwiki.wikia.com/wiki/Warsong_Gulch

Battlefields:
- Warsong Gulch
- Arathi Basin
- Eye of the Storm

Thank @DankoDJ, for reminding us that we must do homework.

**Comment by DankoDJ** [comment] 2016-01-17 15:17
Should I close it as "not reproduceable"?
Do you mean player restoration, or npc restoration?
Normal restoration or are we talking about potion/spell effects?
... in any battlefield.... please check out our readme file, I know it is hard to describe how it is reproduceable but please try it, invest more than 10 seconds for new issues... we have to ask nearly the same questions for nearly all new issues...

**Comment by Zyres** [comment] 2016-01-17 15:36
I think he means the restoration (areatrigger) in specific areas, like https://github.com/AscEmu/AscEmu/blob/master/src/scripts/Battlegrounds/WarsongGulch.cpp#L129

**Comment by DankoDJ** [comment] 2016-01-18 09:46
Info (just for me):
SpellEntry: 23493 http://www.wowhead.com/spell=23493/restoration
GoEntry: 179904 / 179906

SpellEntry: 24379 http://www.wowhead.com/spell=24379/restoration
GoEntry: 180144 / 180145 / 180362 / 180377 / 180383 / 184965 / 184971 / 184974 / 184977

Both spells are in Hackfixes.cpp (is this really necessary?).
Add a proper handler for these to Aura::SpellAuraPeriodicTrigger (not sure) get the health/mana from player and restore every secon 1/10th of it.

**Closed** 2016-01-20 00:17 UTC
Labels: Spells

**Comment by Zyres** [comment] 2016-01-20 00:18
@armm77 give me a sign if the problem is not solved.

**Comment by armm77** [comment] 2016-01-20 03:43
@Zyres, works but not properly, in the case of mana when it reaches the 50% down to 48% and rises again, and keeps repeating in higher percentages, I think it's a defect in the function of calculation of mana because it also presents the fails when the character's mana potion is taken. (42545 Runic Mana Injector)
